HelpDesk.WebUI/Controllers/OperatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using HelpDesk.BLL;
using HelpDesk.BLL.Repository;
using HelpDesk.BLL.Repository.Abstracts;
using HelpDesk.Model.Entities.Poco;
using HelpDesk.Model.ViewModels.FaultViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Design;

namespace HelpDesk.WebUI.Controllers
{
    public class OperatorController : Controller
    {
        private readonly IRepoIdentity _userRoleRepo;
        private readonly MembershipTools _membershipTools;
        private readonly Operator_Repo _operatorRepo;
        private readonly IHostingEnvironment _hostingEnvironment;

        public OperatorController(IRepoIdentity userRoleRepo, MembershipTools membershipTools, Operator_Repo operatorRepo, IHostingEnvironment hostingEnvironment)
        {
            _userRoleRepo = userRoleRepo;
            _membershipTools = membershipTools;
            _operatorRepo = operatorRepo;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {

            var UnapprovedRecords = _operatorRepo.GetUnApproveRecords();
            //var data = new ArizaKayitRepo()
            //   .GetAll(x => x.OperatorKabul == false)
            //   .Select(x => Mapper.Map<ArizaViewModel>(x))
            //   .ToList();
            if (UnapprovedRecords == null)
            {
                TempData["Message"] = "Bir hata oluştu. Tekrar Deneyiniz";
                return View();
            }
            else
            {
                var data = Mapper.Map<List<FaultViewModels>>(UnapprovedRecords);

                return View(data);
            }
            //return View(data);

           
        }

        [HttpGet]
        public async Task<IActionResult> FaultDetail(int id)
        {
            //try
            //{

            //    var x = new ArizaKayitRepo().GetById(id);

            //    var data = Mapper.Map<ArizaViewModel>(x);
            //    data.ArızaPath = new FotografRepo().GetAll(z => z.ArizaId == id).Select(u => u.Yol).ToList();

            //    return View(data);
            //}
            //catch (Exception ex)
            //{
            //    TempData["Model"] = new ErrorViewModel()
            //    {
            //        Text = $"Bir hata oluştu {ex.Message}",
            //        ActionName = "Index",
            //        ControllerName = "Admin",
            //        ErrorCode = 500
            //    };
            //    return RedirectToAction("Error", "Home");
            //}
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> FaultAccept(int id)
        {
            return View();
            ////ikisiylede bulabilirsin o anki sistemde online olanı
            ////var OpertatorId = HttpContext.User.Identity.GetUserId();

            //var OpertatorId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            //try
            //{
            //    var ariza = await new ArizaKayitRepo().GetByIdAsync(id);
            //    var Operator = await NewUserManager().FindByIdAsync(OpertatorId);
            //    if (ariza == null)
            //    {
            //        RedirectToAction("Index", "Operator");
            //    }
            //    else
            //    {
            //        ariza.OperatorKabulTarih = DateTime.Now;
            //        ariza.OperatorKabul = true;
            //        ariza.OperatorId = OpertatorId;
            //        ariza.ArizaDurumu = ArizaDurum.OperatorTakibeAldı;
            //        new ArizaKayitRepo().Update(ariza);
            //        var OperatorLog = new ArizaLOG
            //        {
            //            CreatedDate = DateTime.Now,
            //            ArızaId = id,
            //            Aciklama = $"Ariza'nız {Operator.Name} {Operator.Surname} isimli Operator Tarafından Onaylanmıştır.",
            //            YapanınRolu = IdentityRoles.Teknisyen
            //        };
            //        new ArizaLogRepo().Insert(OperatorLog);
            //        return RedirectToAction("Index", "Operator");
            //        //TODO Müşteriye Mail gönderilir bilgilendirme belki
            //    }

            //    return RedirectToAction("Index", "Operator");

            //}

            //catch (Exception ex)
            //{
            //    TempData["Model"] = new ErrorViewModel()
            //    {
            //        Text = $"Bir hata oluştu {ex.Message}",
            //        ActionName = "Index",
            //        ControllerName = "Admin",
            //        ErrorCode = 500
            //    };
            //    return RedirectToAction("Error", "Home");
            //}
        }
        public IActionResult OpeFaultDetail(int id)
        {
            //try
            //{
            //    var ariza = new ArizaKayitRepo().GetById(id);
            //    var data = Mapper.Map<ArizaViewModel>(ariza);
            //    data.ArızaPath = new FotografRepo().GetAll(z => z.ArizaId == id).Select(u => u.Yol).ToList();
            //    ViewBag.TeknisyenK = BostaOlanTeknisyenler(data);



            //    return View(data);
            //}
            //catch (Exception ex)
            //{
            //    Console.WriteLine(ex);
            //    throw;
            //}
            return View();
        }
    }
}

HelpDesk.WebUI/Views/Operator/FaultDetail.cshtml
@model HelpDesk.Model.ViewModels.FaultViewModels.FaultViewModels
@using HelpDesk.BLL
@inject MembershipTools membership
@{
    ViewData["Title"] = "FaultDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section top{
    <link href="~/assets/css/lightbox.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/js/plugins/slick/slick.min.css" />
    <link rel="stylesheet" href="~/assets/js/plugins/slick/slick-theme.min.css" />
}
<h2 class="text-center">Fault Detail</h2>
<div class="col-md-6 col-md-offset-3">
    <div class="card">
        <div class="card-block tab-content">
            <div class="tab-pane fade active in" id="profile-tab1">
                <form asp-controller="Operator" asp-action="FaultRecordAdd" method="post" class="fieldset">

                    @*var data = membership.GetUserWithId(User.Result.CustomerId);*@

                    <h4 class="m-t-sm m-b">Fault Record Information</h4>
                    <div class="form-group row">
                        <div class="col-xs-6">
                         <label for="Name">Müşterinin Adı</label>
                           <input type="text" for="data.Name" class="form-control" placeholder="İsim giriniz" />
                        </div>
                        <div class="col-xs-6">
                            <label for="Surname">Müşterinin Soyadı</label>
                            <input type="text" for="Surname" class="form-control" placeholder="Soyisim giriniz" />                          
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-xs-6">
                            <label for="Email">Müşterinin Maili</label>
                            <input type="text" for="Email" class="form-control" placeholder="Mail giriniz" />                         
                        </div>
                        <div class="col-xs-6">
                            <label asp-for="PhoneNumber">Telefon</label>
                            <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="Telefon numarası giriniz" />                         
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Adress">Arıza Açıklaması</label>
                        <input type="text" asp-for="Adress" class="form-control" placeholder="Adres bilgisi giriniz" />
                    </div>

                    <div class="form-group row">
                        <div class="col-xs-6">
                          
                            <label asp-for="PostedFileFault">Arıza Resmi</label>
                            <input type="file" asp-for="PostedFileFault" class="form-control" multiple="true" placeholder="ADRESSSs" />
                        </div>
                        </div>
                    <div class="col-xs-6">
                      
                        <label asp-for="PostedFileFatura">Arıza Resmi</label>
                        <input type="file" asp-for="PostedFileFatura" class="form-control" placeholder="ADRESSSs" />
                    </div>
                    </div>
                    <div class="row narrow-gutter">
                        <div class="col-xs-12">
                            @*<a href="@Url.Action("ArizaKabul", "Operator", new {id = Model.ArizaId})" class="btn btn-app btn-block hidden-xs" title="Arıza Kabul">
                                Arızayı Onayla
                            </a>*@
                            <a asp-controller="Operator" asp-action="FaultAccept" class="btn btn-app btn-block" asp-route-id="@Model.FaultId">Fault Accept</a>
                            @*Id yi nasıl göndercem bulamadım..*@
                        </div>
                    </div>
                </form>
            </div>
            <!-- End profile tab 1 -->
        </div>
        <!-- .card-block .tab-content -->
    </div>
    <!-- .card -->
</div>
@section bottom{
    <script src="~/assets/js/plugins/slick/slick.min.js"></script>
    <script src="~/assets/js/lightbox-plus-jquery.min.js"></script>
    <script src="~/assets/js/lightbox.js"></script>
    <script>$(function () {
            // Init page helpers (Slick Slider plugin)
            App.initHelpers('slick');
        });</script>
}

HelpDesk.WebUI/Views/Operator/Index.cshtml
@using HelpDesk.BLL.Repository.Fault_Repo
@model List<HelpDesk.Model.ViewModels.FaultViewModels.FaultViewModels>
@using HelpDesk.BLL
@inject MembershipTools membership
@inject Fault_Repo faultrepo
@using HelpDesk.Model.Entities.Poco
@using HelpDesk.Model.Enums.FaultEnums

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    //TODO BUNU NASIL EKLİCEZ İSMOOO

    //var teknisyenId = HttpContext.Current.User.Identity.GetUserId();
    //var TeknisyeneAitList = new ArizaKayitRepo().GetAll(x => x.OperatorId == teknisyenId).OrderBy(x => x.ArizaOlusturmaTarihi).ToList();
    var technician = membership.GetCurrentUser(User);
    var TechnicianList = faultrepo.GetAll(x => x.OperatorId == technician.Result.Id).OrderBy(x => x.FaultCreatedDate).ToList();
}

@section top
    {
    <!-- Page JS Plugins CSS -->
    <link rel="stylesheet" href="~/assets/js/plugins/datatables/jquery.dataTables.min.css" />
    <link rel="stylesheet" id="css-font-awesome" href="~/assets/css/font-awesome.css" />
    <link rel="stylesheet" id="css-ionicons" href="~/assets/css/ionicons.css" />
}
<div class="card-header">
    @*TODO YAPILACAK*@
    <h5 class="text-center">Merhaba @*@MembershipTools.GetNameSurname*@(null) - İyi Çalışmalar Dileriz. FiTech<span class="ion-alert"></span></h5><br />
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-success">
            <p><strong>Başarılı! </strong> @TempData["Message"]</p>
        </div>
    }
</div>
<div class="card">

    <div class="card-block">
        <table class="table table-bordered table-striped table-vcenter dataTable">
            <thead>
                <tr>
                    <th class="text-center">Fault Record No</th>
                    <th class="text-center">Fault Condition</th>
                    <th class="text-center">Technician Name</th>
                    <th class="text-center">Technician Phone</th>
                    <th class="text-center">Technician Fault State</th>
                    <th class="text-center">Technician Fault Description</th>
                    <th class="text-center" style="width: 10%;">Technician Assign</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < TechnicianList.Count; i++)
                {
                    var dataTeknisyen = membership.GetUserWithId(TechnicianList[i].TechnicianId);

                    var data2 = TechnicianList[i];

                        <tr class="@(data2.OperatorAccept==false ? "bg-red":"bg-green")">
                            <td class="font-300 text-center">@(i + 1)</td>
                            <td class="font-300 text-center">@(data2.FaultCondition)</td>
                            <td class="font-300 text-center">@((data2.TechnicianId == null) ? "Teknisyen Atanmadı" : dataTeknisyen.Result.Name + " " + dataTeknisyen.Result.Surname)</td>
                            <td class="font-300 text-center">@((data2.TechnicianId == null) ? "Teknisyen atanmadı" : data2.PhoneNumber)</td>
                            <td class="font-300 text-center">@(data2.TechnicianFailureStatus ?? TechnicianFailureStatus.Unchecked)</td>
                            <td class="font-300 text-center">@(data2.TechnicialFaultDescription ?? "Kontrol Edilmedi")</td>
                            <td class="text-center">
                                <div class="btn-group">
                                        <a asp-controller="Operator" asp-action="OpeFaultDetail" class="btn btn-app btn-block" asp-route-id="data2.Id">Assign Technician</a>
                                        <i class="ion-android-arrow-up">Technician Assign & Detail</i>
                                </div>
                            </td>
                        </tr>
                    }
            </tbody>
        </table>
    </div>
    <!-- .card-block -->
</div>


<div class="card">
    <div class="card-header">

        <h4 class="text-center">Onaylanmamış Arıza Listesi</h4>
    </div>
    <div class="card-block">
        <!-- DataTables init on table by adding .js-dataTable-full class, functionality initialized in js/pages/base_tables_datatables.js -->
        <table class="table table-bordered table-striped table-vcenter dataTable">
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th>Photo</th>
                    <th>User Name</th>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Created Date</th>
                    <th>Adress</th>
                    <th class="text-center" style="width: 10%;">Detail</th>
                </tr>
            </thead>
            
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {

                    var data = membership.GetUserWithId(Model[i].CustomerId);
                    var data2 = Model[i];

                    @*<tr class="@(data.EmailConfirmed?"":"bg-yellow")">*@
                    <tr class="bg-danger">
                            <td class="text-center">@(i + 1)</td>
                            <td class="text-center">
                                <img src="@(string.IsNullOrEmpty(data.Result.AvatarPath)?"/assets/img/avatars/avatar3.jpg":data.Result.AvatarPath)" class="img-avatar-96" width="100" height="100" />
                            </td>
                            <td class="font-500">@data.Result.UserName</td>
                            <td>@data.Result.Name</td>
                            <td>@data.Result.Surname</td>
                            <td>@data2.FaultCreatedDate</td>
                            <td>@data2.Adress</td>

                            <td class="text-center">
                                <div class="btn-group">                                  
                                        <a asp-controller="Operator" asp-action="FaultDetail" class="btn btn-app btn-block" asp-route-id="data2.FaultId">Fault Detail</a>
                                        <i class="ion-edit"></i>                                 
                                </div>
                            </td>
                        </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- .card-block -->
</div>

@section bottom
    {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-3.3.1/dt-1.10.18/af-2.3.2/b-1.5.4/b-colvis-1.5.4/b-flash-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/r-2.2.2/sc-1.5.0/datatables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css" />
    <script src="~/assets/js/plugins/bootstrap-notify/bootstrap-notify.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jq-3.3.1/dt-1.10.18/af-2.3.2/b-1.5.4/b-colvis-1.5.4/b-flash-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/r-2.2.2/sc-1.5.0/datatables.min.js"></script>
    <script>
        $(function () {
            $(".dataTable").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
        });</script>
}

HelpDesk.WebUI/Views/Operator/OpeFaultDetail.cshtml
@model HelpDesk.Model.ViewModels.FaultViewModels.FaultViewModels
@using HelpDesk.Model.Enums.FaultEnums
@using HelpDesk.BLL
@inject MembershipTools membership

@{
    ViewData["Title"] = "OpeFaultDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section top{
    <link href="~/assets/css/lightbox.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/js/plugins/slick/slick.min.css" />
    <link rel="stylesheet" href="~/assets/js/plugins/slick/slick-theme.min.css" />
}
<h2 class="text-center">Teknisyen Atama Ariza Detay</h2>
<div class="col-md-12">
    <div class="card">
        <div class="card-block tab-content">
            <div class="tab-pane fade active in" id="profile-tab1">
               
                    <form asp-controller="Operator" asp-action="TechnicianAssign" method="post" class="fieldset">
                       
                       @*var data = membership.GetUserWithId(Model.CustomerID)*@
                        @Html.HiddenFor(x => x.FaultId)

                        <h4 class="m-t-sm m-b">Teknisyen Atama Sayfası</h4>
                        <br />

                        <div class="form-group row">
                            <div class="col-md-12">
                                <br />
                                @if (Model.FaultCondition != FaultCondition.TechnicianAppointed)
                                {
                                    @*@Html.Label("Teknisyen Seçiniz", new { @class = "col-md-3 control-label" })*@
                                    <label for="">Choose Technician</label>
                                    <div class="col-md-6">
                                        @*TODO buradaki x.UserId sayafaya gelen modelde olmalı. ona göre anlıyor. ve tipi de geldigi gibi olmalı. string geliyorsa string int ise int*@
                                        @*@Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.TeknisyenK, new { @class = "form-control", size = "1" })*@
                                    </div>
                                    <div class="row narrow-gutter">
                                        <div class="col-md-12">
                                            @*Butonlar yapılcak*@
                                            <button class="btn btn-app-purple btn-block" type="submit">Teknisyen Ata</button>
                                        </div>
                                    </div>
                                }
                                else
                                { <div class="row narrow-gutter">
                                        <div class="col-md-12">
                                            <span class="icon-alert"> Bu Kayda Teknisyen Atandı. Detayları Görebilirsiniz. </span>
                                        </div>
                                    </div>

                                }
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-xs-6">
                                <label for="Name">Müşterinin Adı</label>
                                <input type="text" for="data.Name" class="form-control" placeholder="İsim giriniz" />
                            </div>
                            <div class="col-xs-6">
                                <label for="Surname">Müşterinin Soyadı</label>
                                <input type="text" for="Surname" class="form-control" placeholder="Soyisim giriniz" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-xs-6">
                                <label for="Email">Müşterinin Maili</label>
                                <input type="text" for="Email" class="form-control" placeholder="Mail giriniz" />
                            </div>
                            <div class="col-xs-6">
                                <label asp-for="PhoneNumber">Telefon</label>
                                <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="Telefon numarası giriniz" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Adress">Arıza Açıklaması</label>
                            <input type="text" asp-for="Adress" class="form-control" placeholder="Adres bilgisi giriniz" />
                        </div>

                        <div class="form-group row">
                            <div class="col-xs-6">

                                <label asp-for="PostedFileFault">Arıza Resmi</label>
                                <input type="file" asp-for="PostedFileFault" class="form-control" multiple="true" placeholder="ADRESSSs" />
                            </div>
                        </div>
                        <div class="col-xs-6">

                            <label asp-for="PostedFileFatura">Arıza Resmi</label>
                            <input type="file" asp-for="PostedFileFatura" class="form-control" placeholder="ADRESSSs" />
                        </div>



                        </form>
                     
                </div>
            <!-- End profile tab 1 -->
        </div>
        <!-- .card-block .tab-content -->
    </div>
    <!-- .card -->
</div>

@section bottom
    {
    <script src="~/assets/js/plugins/select2/select2.full.min.js"></script>
    <script src="~/assets/js/lightbox-plus-jquery.min.js"></script>
    <script src="~/assets/js/lightbox.js"></script>
    <script>$(function () {
            App.initHelpers(['select2']);

        });</script>
}