HelpDesk.WebUI/Controllers/TechnicianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HelpDesk.Model.ViewModels.FaultViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HelpDesk.WebUI.Controllers
{
    public class TechnicianController : Controller
    {
        public IActionResult Index()
        {
            //try
            //{
            //    //Sistemdeki teknisyenId sini verir.
            //    var teknisyenId = HttpContext.User.Identity.GetUserId();
            //    //arızalar tablosuna sistemdeki teknisyen ıd  alındı ve sorgu atıldı . mapper ile view model e çevrilip sayfaya gönderildi
            //    var data = new ArizaKayitRepo()
            //        .GetAll(x => x.TeknisyenId == teknisyenId).Select(x => Mapper.Map<ArizaViewModel>(x))
            //        .ToList();

            //    return View(data);
            //}
            //catch (Exception ex)
            //{
            //    TempData["Model"] = new ErrorViewModel()
            //    {
            //        Text = $"Bir hata oluştu {ex.Message}",
            //        ActionName = "Index",
            //        ControllerName = "Home",
            //        ErrorCode = 500
            //    };
            //    return RedirectToAction("Error", "Home");
            //}
            return View();
        }
        public IActionResult TechnicianFaultReport(int id)
        {
            //try
            //{
            //    var ariza = new ArizaKayitRepo().GetById(id);
            //    var data = Mapper.Map<ArizaViewModel>(ariza);
            //    data.ArızaPath = new FotografRepo().GetAll(z => z.ArizaId == id).Select(u => u.Yol).ToList();
            //    //ilgili log kayıtları getiriyor. o arizaya ait.
            //    var Logs = new ArizaLogRepo().GetAll()
            //        .Where(u => u.ArızaId == id)
            //        .OrderByDescending(u => u.CreatedDate)
            //        .ToList();
            //    data.ArizaLogs.Clear();

            //    //data.ArizaLogViewModels.Clear();
            //    //gelen logkayitlarini mapper ile view model e çevirip. arizaviewmoedeki alana ekliyoruz.
            //    //BURADA VİEWMODEL YAPAMADIK NEDEN BAK SOR ...
            //    foreach (ArizaLOG log in Logs)
            //    {

            //        data.ArizaLogs.Add(log);
            //    }
            //    return View(data);

            //}
            //catch (Exception ex)
            //{
            //    TempData["Model"] = new ErrorViewModel()
            //    {
            //        Text = $"Bir hata oluştu {ex.Message}",
            //        ActionName = "Index",
            //        ControllerName = "Home",
            //        ErrorCode = 500
            //    };
            //    return RedirectToAction("Error", "Home");

            //}
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> TechnicianFaultConfirm(FaultViewModels model)
        {
            //try
            //{


            //    var ariza = await new ArizaKayitRepo().GetByIdAsync(model.ArizaId);
            //    if (model.TeknisyenArizaDurum == null)
            //    {
            //        return RedirectToAction("TeknisyenArizaRapor", "Teknisyen", model);
            //    }
            //    ariza.TeknisyenArizaAciklama = model.TeknisyenArizaAciklama;
            //    ariza.TeknisyenArizaDurum = model.TeknisyenArizaDurum;
            //    ariza.ArizaSonKontrolTarihi = DateTime.Now;
            //    var TeknisyenId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            //    var teknisyen = await NewUserManager().FindByIdAsync(TeknisyenId);
            //    var musteri = NewUserManager().FindById(model.MusteriId);
            //    var Operator = NewUserManager().FindById(model.OperatorId);
            //    //musteri ıd vs gelmiyor onları getir . userı bul mail e gönder

            //    if (model.TeknisyenArizaDurum == TeknisyenArizaDurum.Çözüldü)
            //    {
            //        ariza.ArizaCozulduguTarih = DateTime.Now;
            //        var user = NewUserManager().FindById(model.MusteriId);
            //        ariza.TeknisyenDurumu = TeknisyenDurumu.Bosta;
            //        ariza.AnketCode = StringHelpers.GetCode();
            //        new ArizaKayitRepo().Update(ariza);


            //        string SiteUrl = Request.Url.Scheme + System.Uri.SchemeDelimiter + Request.Url.Host +
            //                         (Request.Url.IsDefaultPort ? "" : ":" + Request.Url.Port);
            //        var emailService = new EmailService();
            //        var body = $"Merhaba {musteri.Name} {musteri.Surname} <b></b><br>FİTech için geri döüşleriniz çok önemli. 5 Dakikanızı ayırarak anketimizi doldurabilirsiniz. Aşagıdaki Linke tıklayarak anket sayfasına gidebilirsiniz.<br> <a href='{SiteUrl}/Anket/Index?code={ariza.AnketCode}' >Anket'e Gitmek için Tıklayınız. </a> ";

            //        await emailService.SendAsync(new IdentityMessage()
            //        {

            //            Body = body,
            //            Subject = "Anket"
            //        }, model.Email);
            //        var emailService2 = new EmailService();
            //        //TODO Acaba buradada kontrol eedildimi edilmedimi kontrol etmeye gerek var mı ?
            //        var body2 = $"Merhaba {Operator.Name} {Operator.Surname} <b></b><br>{teknisyen.Name} {teknisyen.Surname} isimli calısanımıza {model.TeknisyenAtandigiTarih}'de atamıs oldugunuz Arizanın çözüldügünü iletti. Kontrol etmek için aşagıdaki link'e tıklayınız.<br> <a href='{SiteUrl}/Teknisyen/TeknisyenArizaRapor/{model.ArizaId}' >Kontrol Etmek için Tıklayınız. </a> ";
            //        await emailService2.SendAsync(new IdentityMessage()
            //        {
            //            Body = body2,
            //            Subject = "Kontrol"
            //        }, Operator.Email);
            //    }

            //    var TeknisyenLog = new ArizaLOG
            //    {
            //        ArızaId = model.ArizaId,
            //        YapanınRolu = IdentityRoles.Teknisyen,
            //        CreatedDate = DateTime.Now,
            //        Aciklama = $"Arıza Kontrol Edildi. Kontrol sonucu {model.TeknisyenArizaAciklama} notu bırakıldı .Son Durum {model.TeknisyenArizaDurum}",

            //    };
            //    new ArizaLogRepo().Insert(TeknisyenLog);
            //    TempData["Message"] = $"{model.ArizaId} no lu Kayıt Raporu Alınmıştır. İyi çalışamlar";
            //    return RedirectToAction("Index", "Teknisyen");

            //}
            //catch (Exception ex)
            //{
            //    TempData["Model"] = new ErrorViewModel()
            //    {
            //        Text = $"Bir hata oluştu {ex.Message}",
            //        ActionName = "Index",
            //        ControllerName = "Teknisyen",
            //        ErrorCode = 500
            //    };
            //    return RedirectToAction("Error", "Home");
            //}
            return View();
        }
    }


    }
}

HelpDesk.WebUI/Views/Technician/Index.cshtml
@using HelpDesk.BLL
@using HelpDesk.Model.Enums.FaultEnums
@model List<HelpDesk.Model.ViewModels.FaultViewModels.FaultViewModels>
@inject MembershipTools membership

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section top
    {
    <!-- Page JS Plugins CSS -->
    <link rel="stylesheet" href="~/assets/js/plugins/datatables/jquery.dataTables.min.css" />
}
<div class="card">
    <div class="card-header">
        <h4 class="text-center">Teknisyen Arıza Sayfası</h4>
    </div>
    <div class="card-header">
        <h4 class="text-center">Merhaba @membership.GetCurrentUser(null)</h4><br />
    </div>
    <div class="card-header">
        <h4 class="text-center">İyi Çalışmalar Dileriz. Müşteri BaşTACIDIR. ONA GÖRE RAKO FiTech<span class="ion-alert"></span></h4>
    </div>
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-success">
            <p><strong>Başarılı!</strong> @TempData["Message"]</p>
        </div>
    }
    <div class="card-block">
        <!-- DataTables init on table by adding .js-dataTable-full class, functionality initialized in js/pages/base_tables_datatables.js -->
        <table class="table table-bordered table-striped table-vcenter dataTable">
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th>Photo</th>>
                    <th>Customer Name</th>
                    <th>Customer Surname</th>
                    <th>Atayan Operator</th>
                    <th>Created Date</th>
                    <th>Adress</th>
                    <th>Fault Description</th>
                    <th>Fault Last Condition</th>
                    <th class="text-center" style="width: 10%;">Detail</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {

                    var data = membership.GetUserWithId(Model[i].CustomerId);
                    var data1 = membership.GetUserWithId(Model[i].OperatorId);
                    var data2 = Model[i];

                    @*<tr class="@(data.EmailConfirmed?"":"bg-yellow")">*@
                    <tr class="bg-danger">
                        <td class="text-center">@(i + 1)</td>
                        <td class="text-center">
                            <img src="@(string.IsNullOrEmpty(data.Result.AvatarPath)?"/assets/img/avatars/avatar3.jpg":data.Result.AvatarPath)" class="img-avatar-96" width="100" height="100" />
                        </td>
                        <td>@data.Result.Name</td>
                        <td>@data.Result.Surname</td>
                        <td>@($"{data1.Result.Name} {data1.Result.Surname}")</td>
                        <td>@data2.FaultCreatedDate</td>
                        <td>@data2.Adress</td>
                        <td>@data2.FaultDescription</td>
                        <td>@(data2.TechnicianFailureCondition == null ? TechnicianFailureStatus.Unchecked : data2.TechnicianFailureCondition)</td>

                        <td class="text-center">
                           <div class="btn-group">                     
                                    <a asp-controller="Technician" asp-action="TechnicianFaultReport" class="btn btn-app btn-block" asp-route-id="data2.FaultId">Fault </a>
                                    <i class="ion-edit"></i>                             
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- .card-block -->
</div>

@section bottom
    {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jq-3.3.1/dt-1.10.18/af-2.3.2/b-1.5.4/b-colvis-1.5.4/b-flash-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/r-2.2.2/sc-1.5.0/datatables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css" />
    <script src="~/assets/js/plugins/bootstrap-notify/bootstrap-notify.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jq-3.3.1/dt-1.10.18/af-2.3.2/b-1.5.4/b-colvis-1.5.4/b-flash-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/r-2.2.2/sc-1.5.0/datatables.min.js"></script>
    <script>
    $(function () {
            $(".dataTable").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
        });</script>
}

HelpDesk.WebUI/Views/Technician/TechnicianFaultReport.cshtml
@using HelpDesk.BLL
@model HelpDesk.Model.ViewModels.FaultViewModels.FaultViewModels
@using HelpDesk.Model.Enums.FaultEnums
@inject MembershipTools membership
@{
    ViewData["Title"] = "TechnicianFaultReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section top{
    <link href="~/assets/css/lightbox.min.css" rel="stylesheet" />
}
<h2 class="text-center">Teknisyen Arıza Kontrol Raporu</h2>
<div class="col-md-8">
    <div class="card">
        <div class="card-block tab-content">
            <div class="tab-pane fade active in" id="profile-tab1">
                <form asp-controller="Technician" asp-action="TechnicianFaultConfirm" method="post">



                    var data = MembershipTools.GetMusteri(Model.MusteriId);

                    @Html.HiddenFor(x => x.FaultId)
                    @Html.HiddenFor(x => x.CustomerId)
                    @Html.HiddenFor(x => x.Email)
                    @Html.HiddenFor(x => x.OperatorId)
                    <h4 class="m-t-sm m-b">Arıza Kontrol Bildiri</h4>
                    <div class="form-group row">
                        <div class="col-xs-6">
                            <label for="Name">Müşterinin Adı</label>
                            <input type="text" for="data.Name" class="form-control" placeholder="İsim giriniz" />
                        </div>
                        <div class="col-xs-6">
                            <label for="Surname">Müşterinin Soyadı</label>
                            <input type="text" for="Surname" class="form-control" placeholder="Soyisim giriniz" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-xs-6">
                            <label for="Email">Müşterinin Maili</label>
                            <input type="text" for="Email" class="form-control" placeholder="Mail giriniz" />
                        </div>
                        <div class="col-xs-6">
                            <label asp-for="PhoneNumber">Telefon</label>
                            <input type="text" asp-for="PhoneNumber" class="form-control" placeholder="Telefon numarası giriniz" />
                        </div>
                    </div>

                    @if (Model.TechnicianFailureCondition != TechnicianFailureStatus.Solved)
                    {
                    <div class="form-group row">
                        <div class="col-xs-12">
                            <label asp-for="TechnicianFailureCondition">Fault State</label>                           
                        </div>
                        @*BURAYI NASIL YAPACAĞIMI BULAMADIM...*@
                        @*<div class="col-xs-12">
                            @Html.EnumDropDownListFor(x => x.TeknisyenArizaDurum, "Arızanın Son Durumu", new { @class = "form-control", size = "1" })<select asp-for="TechnicianFailureCondition" asp-items=""></select>                          
                        </div>*@
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <label asp-for="TechnicialFaultDescription">Ariza Açıklması</label>
                            <input type="text" asp-for="TechnicialFaultDescription" class="form-control" placeholder="Lütfen arıza açıklması giriniz" />                         
                        </div>
                    </div>
                    }
                    else
                    {
                    <div class="form-group row">
                        <div class="col-xs-12">
                            <label asp-for="TechnicianFailureCondition">Teknisyen Arıza Durumu</label>                          
                        </div>
                        @*<div class="col-xs-12">
                            @Html.EnumDropDownListFor(x => x.TeknisyenArizaDurum, "Arızanın Son Durumu", new { @class = "form-control", @readonly = "readonly", size = "1" })
                        </div>*@
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <label asp-for="TechnicialFaultDescription">Ariza Açıklması</label>
                            <input type="text" asp-for="TechnicialFaultDescription" class="form-control" placeholder="Lütfen arıza açıklması giriniz" />
                        </div>
                    </div>
                    }
                    <div class="form-group row">
                        <div class="col-xs-6">
                            <label asp-for="PostedFileFault">Arıza Resmi</label>
                            <input type="file" asp-for="PostedFileFault" class="form-control" multiple="true" placeholder="ADRESSSs" />
                            <div class="col-xs-6">
                                <label asp-for="PostedFileFatura">Arıza Resmi</label>
                                <input type="file" asp-for="PostedFileFatura" class="form-control" placeholder="ADRESSSs" />
                            </div>

                    <div class="row narrow-gutter">
                        @if (Model.TechnicianFailureCondition != TechnicianFailureStatus.Solved)
                        {
                            <div class="col-xs-12">
                                <div class="col-md-12">
                                    <button class="btn btn-app-purple btn-block" type="submit">Arıza Kontrol Raporu Gönder</button>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="row narrow-gutter">
                                <div class="col-md-12">
                                    <span class="icon-alert"> Bu Kayıt Çözülmüştür. Sadece Detayları Görebilirsiniz. </span>
                                </div>
                            </div>
                        }
                    </div>

                </form>
            </div>
            <!-- End profile tab 1 -->
        </div>
        <!-- .card-block .tab-content -->
    </div>
    <!-- .card -->
</div>
@*<div class="col-md-4">
    <div class="panel">
        <div class="panel-heading">



            <h3 class="panel-title">Olaylar</h3><h3></h3>
        </div><br />
        <div class="panel-body">
            <div class="timeline">
                <!-- Timeline header -->
                <div class="timeline-header">
                    <div class="timeline-header-title bg-info">Şimdi</div>
                </div>
                @foreach (ArizaLOG log in Model.ArizaLogs)
                {
                    <div class="timeline-entry">
                        <div class="timeline-stat">
                            @switch (log.YapanınRolu)
                            {
                                case IdentityRoles.Operator:
                                    <div class="timeline-icon bg-success"><i class="fa fa-clipboard fa-lg"></i> </div>
                                    break;
                                case IdentityRoles.Musteri:
                                    <div class="timeline-icon bg-info"><i class="fa fa-check fa-lg"></i> </div>
                                    break;
                                case IdentityRoles.Teknisyen:
                                    <div class="timeline-icon bg-warning"><i class="fa fa-briefcase fa-lg"></i> </div>
                                    break;
                                default:
                                    <div class="timeline-icon bg-purple"><i class="fa fa-check fa-lg"></i> </div>
                                    break;
                            }
                        </div>
                        <div class="timeline-label">
                            @log.CreatedDate
                            <h3>@log.Aciklama</h3>
                        </div>
                    </div>
                }
            </div>
        </div>
        <!--===================================================-->
        <!-- End Striped Table -->
    </div>
</div>*@

@section bottom{
    <script src="~/assets/js/lightbox-plus-jquery.min.js"></script>
    <script src="~/assets/js/lightbox.js"></script>
}